name: Create Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]
  workflow_dispatch:
    

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
    
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    
jobs:

  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Calculate commit hash for PR commit
        if: github.event_name == 'pull_request'
        run: echo "COMMIT_HASH=$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

      - name: Calculate commit hash for merge commit
        if: github.event_name != 'pull_request'
        run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Login to dockerhub
        run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  docker.io

      - name: Build and push container image
        run: |
          CONTAINER_TAG="${{ env.BRANCH_NAME }}-$COMMIT_HASH"
          docker build -t ${{ secrets.DOCKER_HUB_ORG }}/lightwalletd:"$CONTAINER_TAG" -t ${{ secrets.DOCKER_HUB_ORG }}/lightwalletd:${{ env.BRANCH_NAME }}-latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_ORG }}/lightwalletd:"$CONTAINER_TAG"
          docker push ${{ secrets.DOCKER_HUB_ORG }}/lightwalletd:${{ env.BRANCH_NAME }}-latest
